name: Full K8s Deployment with Template
on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SSH Key
        run: |
          mkdir -p /root/.ssh
          if [ ! -f /root/.ssh/id_ed25519 ]; then
            ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N "" -q
          fi
          echo "=== SSH Public Key ==="
          cat /root/.ssh/id_ed25519.pub
          echo "=== SSH Key Fingerprint ==="
          ssh-keygen -l -f /root/.ssh/id_ed25519

      - name: Check IP Availability
        run: |
          echo "=== Проверка доступности IP адреса ==="
          
          # Читаем конфигурацию
          if [ ! -f config.auto.tfvars ]; then
            echo "❌ Файл config.auto.tfvars не найден!"
            exit 1
          fi
          
          # Извлекаем subnet и static_ip_base
          SUBNET=$(grep -oP 'subnet\s*=\s*"\K[^"]+' config.auto.tfvars)
          STATIC_BASE=$(grep -oP 'static_ip_base\s*=\s*\K\d+' config.auto.tfvars)
          
          if [ -z "$SUBNET" ] || [ -z "$STATIC_BASE" ]; then
            echo "❌ Не удалось прочитать subnet или static_ip_base"
            exit 1
          fi
          
          # Получаем IP адрес
          NETWORK_PREFIX=$(echo $SUBNET | cut -d'/' -f1 | sed 's/\.[0-9]*$/.&/')
          NETWORK_PREFIX=${NETWORK_PREFIX%.*}
          PLANNED_IP="${NETWORK_PREFIX}.${STATIC_BASE}"
          
          echo "Сеть: $SUBNET"
          echo "Планируемый IP: $PLANNED_IP"
          
          # Проверяем доступность
          echo -n "Проверка $PLANNED_IP ... "
          if ping -c 2 -W 1 "$PLANNED_IP" &> /dev/null; then
            echo "ЗАНЯТ ⚠️"
            echo "❌ IP адрес $PLANNED_IP уже используется в сети!"
            echo "Измените static_ip_base в config.auto.tfvars и перезапустите"
            exit 1
          else
            echo "СВОБОДЕН ✅"
          fi

      - name: Show Configuration
        run: |
          echo "=== Config.auto.tfvars ==="
          cat config.auto.tfvars
          echo ""
          echo "=== Структура проекта ==="
          find . -name "*.tf" -o -name "*.tfvars" | sort

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
