name: Deploy K8s Cluster
on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy config to all directories
        run: |
          echo "=== Копируем config.auto.tfvars во все нужные директории ==="
          cp config.auto.tfvars master/
          cp config.auto.tfvars worker/
          cp config.auto.tfvars template/
          echo "✅ Конфиг скопирован"

      - name: Generate SSH Key
        run: |
          mkdir -p /root/.ssh
          rm -f /root/.ssh/id_ed25519 /root/.ssh/id_ed25519.pub
          ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N "" -q <<< y 2>&1
          echo "✅ SSH ключ сгенерирован"

      - name: Auto-find Free IP Range
        run: |
          echo "=== Автопоиск свободных IP ==="
          
          CONFIG="config.auto.tfvars"
          [ -f "$CONFIG" ] || { echo "❌ $CONFIG не найден"; exit 1; }
          
          SUBNET=$(grep 'subnet' "$CONFIG" | cut -d'"' -f2)
          CURRENT_BASE=$(grep 'static_ip_base' "$CONFIG" | awk '{print $3}')
          MASTERS=$(grep 'masters_count' "$CONFIG" | awk '{print $3}')
          WORKERS=$(grep 'workers_count' "$CONFIG" | awk '{print $3}')
          
          [ -z "$SUBNET" ] && SUBNET="192.168.0.0/24"
          [ -z "$CURRENT_BASE" ] && CURRENT_BASE=110
          [ -z "$MASTERS" ] && MASTERS=1
          [ -z "$WORKERS" ] && WORKERS=2
          
          TOTAL=$((MASTERS + WORKERS))
          NETWORK_PREFIX=$(echo "$SUBNET" | cut -d'/' -f1 | cut -d. -f1-3)
          
          echo "Ищем $TOTAL свободных IP..."
          
          for start in $(seq 120 240); do
            FREE=true
            for offset in $(seq 0 $((TOTAL - 1))); do
              IP="$NETWORK_PREFIX.$((start + offset))"
              if ping -c 1 -W 1 "$IP" >/dev/null 2>&1; then
                FREE=false
                break
              fi
            done
            
            if [ "$FREE" = true ]; then
              echo "✅ Найден свободный диапазон: $start"
              sed -i "s/static_ip_base = $CURRENT_BASE/static_ip_base = $start/" "$CONFIG"
              echo "Обновлено: static_ip_base = $start"
              
              # Также обновляем в скопированных файлах
              for dir in master worker template; do
                if [ -f "$dir/config.auto.tfvars" ]; then
                  sed -i "s/static_ip_base = $CURRENT_BASE/static_ip_base = $start/" "$dir/config.auto.tfvars"
                fi
              done
              
              echo "IP адреса:"
              for i in $(seq 0 $((TOTAL - 1))); do
                echo "  $NETWORK_PREFIX.$((start + i))"
              done
              exit 0
            fi
          done
          
          echo "❌ Свободный диапазон не найден"
          exit 1

      - name: Clean Terraform Cache
        run: |
          echo "=== Очистка кэша Terraform ==="
          for dir in master worker template; do
            if [ -d "$dir" ]; then
              echo "Очищаем $dir/"
              cd "$dir" && rm -rf .terraform .terraform.lock.hcl 2>/dev/null || true
              cd ..
            fi
          done

      - name: Terraform Init (All Modules)
        run: |
          echo "=== Инициализация всех модулей ==="
          for dir in template master worker; do
            if [ -d "$dir" ]; then
              echo "Инициализируем $dir/"
              cd "$dir"
              terraform init
              cd ..
            fi
          done
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Plan (All Modules)
        run: |
          echo "=== План для всех модулей ==="
          for dir in template master worker; do
            if [ -d "$dir" ]; then
              echo "План для $dir/"
              cd "$dir"
              terraform plan -input=false -out="$dir-tfplan"
              cd ..
            fi
          done
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Apply (All Modules)
        run: |
          echo "=== Применение всех модулей ==="
          # Сначала template, потом master, потом worker
          for dir in template master worker; do
            if [ -d "$dir" ]; then
              echo "Применяем $dir/"
              cd "$dir"
              terraform apply -input=false -auto-approve "$dir-tfplan"
              cd ..
            fi
          done
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
