name: Deploy K8s Cluster
on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Parse network configuration
        run: |
          echo "=== Парсим конфигурацию сети ==="
          CONFIG="config.auto.tfvars"
          
          # Извлекаем сеть из конфига
          SUBNET=$(grep 'subnet' "$CONFIG" | cut -d'"' -f2)
          GATEWAY=$(grep 'gateway' "$CONFIG" | cut -d'"' -f2)
          
          if [ -z "$SUBNET" ] || [ -z "$GATEWAY" ]; then
            echo "❌ Не удалось прочитать network_config из $CONFIG"
            exit 1
          fi
          
          # Извлекаем префикс сети (например, 10.0.0 из 10.0.0.0/24)
          NETWORK_PREFIX=$(echo "$SUBNET" | cut -d'/' -f1 | cut -d. -f1-3)
          
          echo "Сеть: $SUBNET"
          echo "Шлюз: $GATEWAY"
          echo "Префикс: $NETWORK_PREFIX"
          
          # Сохраняем в environment
          echo "NETWORK_PREFIX=$NETWORK_PREFIX" >> $GITHUB_ENV
          echo "SUBNET=$SUBNET" >> $GITHUB_ENV
          echo "GATEWAY=$GATEWAY" >> $GITHUB_ENV

      - name: Generate SSH Key
        run: |
          mkdir -p /root/.ssh
          rm -f /root/.ssh/id_ed25519 /root/.ssh/id_ed25519.pub
          ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N "" -q <<< y 2>&1
          SSH_PUB=$(cat /root/.ssh/id_ed25519.pub)
          echo "SSH_PUB_KEY=$SSH_PUB" >> $GITHUB_ENV

      - name: Auto-find Free IP Range
        run: |
          echo "=== Автопоиск свободных IP в сети $NETWORK_PREFIX.XXX ==="
          
          MASTERS=1
          WORKERS=2
          TOTAL=$((MASTERS + WORKERS))
          
          echo "Ищем $TOTAL свободных IP..."
          
          for start in $(seq 100 240); do
            FREE=true
            for i in $(seq 0 $((TOTAL - 1))); do
              IP="$NETWORK_PREFIX.$((start + i))"
              if ping -c 1 -W 1 "$IP" >/dev/null 2>&1; then
                echo "  $IP занят"
                FREE=false
                break
              fi
            done
            
            if [ "$FREE" = true ]; then
              echo "✅ Найден свободный диапазон: $start"
              echo "IP адреса:"
              for i in $(seq 0 $((TOTAL - 1))); do
                echo "  $NETWORK_PREFIX.$((start + i))"
              done
              
              # Записываем в файл для использования в Terraform
              echo "static_ip_base = $start" >> config.auto.tfvars
              echo "static_ip_base = $start" >> master/config.auto.tfvars
              echo "static_ip_base = $start" >> worker/config.auto.tfvars
              echo "GATEWAY=$GATEWAY" >> $GITHUB_ENV
              echo "STATIC_IP_BASE=$start" >> $GITHUB_ENV
              exit 0
            fi
          done
          
          echo "❌ Свободный диапазон не найден"
          exit 1

      - name: Copy config to all dirs
        run: |
          cp config.auto.tfvars template/
          cp config.auto.tfvars master/
          cp config.auto.tfvars worker/

      - name: Update SSH key in configs
        run: |
          for dir in template master worker; do
            sed -i "s|ssh_public_key = \"\"|ssh_public_key = \"$SSH_PUB_KEY\"|" $dir/config.auto.tfvars
          done

      - name: Terraform Apply
        run: |
          # Сначала шаблон
          echo "=== Создаем шаблон ==="
          cd template
          terraform init
          terraform apply -auto-approve -input=false
          cd ..
          
          # Ждем создания шаблона
          sleep 10
          
          # Потом master и worker
          for dir in master worker; do
            echo "=== Работаем в $dir/ ==="
            cd "$dir"
            terraform init
            terraform apply -auto-approve -input=false
            cd ..
          done
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_gateway: ${{ env.GATEWAY }}
          TF_VAR_static_ip_base: ${{ env.STATIC_IP_BASE }}
