name: Deploy K8s Cluster
on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SSH Key
        run: |
          mkdir -p /root/.ssh
          rm -f /root/.ssh/id_ed25519 /root/.ssh/id_ed25519.pub
          ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N "" -q <<< y 2>&1
          SSH_PUB=$(cat /root/.ssh/id_ed25519.pub)
          echo "SSH_PUB_KEY=$SSH_PUB" >> $GITHUB_ENV

      - name: Auto-find Free IP Range
        run: |
          echo "=== Автопоиск свободных IP ==="
          
          MASTERS=1
          WORKERS=2
          TOTAL=$((MASTERS + WORKERS))
          NETWORK="192.168.0"
          
          echo "Ищем $TOTAL свободных IP..."
          
          for start in $(seq 120 240); do
            FREE=true
            for i in $(seq 0 $((TOTAL - 1))); do
              IP="$NETWORK.$((start + i))"
              if ping -c 1 -W 1 "$IP" >/dev/null 2>&1; then
                echo "  $IP занят"
                FREE=false
                break
              fi
            done
            
            if [ "$FREE" = true ]; then
              echo "✅ Найден свободный диапазон: $start"
              echo "IP адреса:"
              for i in $(seq 0 $((TOTAL - 1))); do
                echo "  $NETWORK.$((start + i))"
              done
              
              # Записываем в файл для использования в Terraform
              echo "static_ip_base = $start" >> config.auto.tfvars
              echo "static_ip_base = $start" >> master/config.auto.tfvars
              echo "static_ip_base = $start" >> worker/config.auto.tfvars
              exit 0
            fi
          done
          
          echo "❌ Свободный диапазон не найден"
          exit 1

      - name: Copy config to all dirs
        run: |
          cp config.auto.tfvars template/
          cp config.auto.tfvars master/
          cp config.auto.tfvars worker/

      - name: Update SSH key in configs
        run: |
          for dir in template master worker; do
            sed -i "s|ssh_public_key = \"\"|ssh_public_key = \"$SSH_PUB_KEY\"|" $dir/config.auto.tfvars
          done

      - name: Terraform Apply
        run: |
          # Сначала шаблон
          echo "=== Создаем шаблон ==="
          cd template
          terraform init
          terraform apply -auto-approve -input=false
          cd ..
          
          # Ждем создания шаблона
          sleep 10
          
          # Потом master и worker
          for dir in master worker; do
            echo "=== Работаем в $dir/ ==="
            cd "$dir"
            terraform init
            terraform apply -auto-approve -input=false
            cd ..
          done
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
