name: Terraform Deploy VM
on: [push]

jobs:
  terraform-deploy:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Local Provider Cache
        run: |
          # Гарантируем существование каталога для плагинов
          mkdir -p /root/.terraform.d/plugins
          # Создаем конфиг, который ПЕРЕХВАТЫВАЕТ ВСЕ запросы к registry.terraform.io
          cat > /tmp/terraform.rc << 'EOF'
          provider_installation {
            filesystem_mirror {
              path    = "/root/.terraform.d/plugins"
              include = ["registry.terraform.io/*/*"]
            }
            # БЛОКИРУЕМ любые попытки обращения к сети за провайдерами
            direct {
              exclude = ["registry.terraform.io/*/*"]
            }
          }
          EOF
          export TF_CLI_CONFIG_FILE=/tmp/terraform.rc
          # Выводим для отладки
          echo "Terraform config file created:"
          cat /tmp/terraform.rc

      - name: Clean Terraform Cache
        run: |
          cd master/
          rm -rf .terraform .terraform.lock.hcl

      - name: Terraform Init & Plan
        run: |
          cd master/
          terraform init
          terraform plan -input=false -out=tfplan
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Apply
        run: |
          cd master/
          terraform apply -input=false -auto-approve tfplan
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
