name: Full K8s Deployment with Template
on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SSH Key
        run: |
          mkdir -p /root/.ssh
          if [ ! -f /root/.ssh/id_ed25519 ]; then
            ssh-keygen -t ed25519 -f /root/.ssh/id_ed25519 -N "" -q
          fi
          echo "=== SSH Public Key ==="
          cat /root/.ssh/id_ed25519.pub

      - name: Auto-find IP Range
        run: |
          echo "=== Автоматический подбор IP диапазона ==="
          
          # Читаем настройки
          SUBNET=$(grep 'subnet' config.auto.tfvars | sed -n 's/.*"\([^"]*\)".*/\1/p')
          CURRENT_BASE=$(grep 'static_ip_base' config.auto.tfvars | awk '{print $3}')
          MASTERS=$(grep -A2 'masters_count' config.auto.tfvars | grep -o '[0-9]\+' | head -1)
          WORKERS=$(grep -A2 'workers_count' config.auto.tfvars | grep -o '[0-9]\+' | head -1)
          TOTAL=$((MASTERS + WORKERS))
          
          NETWORK_PREFIX=$(echo "$SUBNET" | cut -d'/' -f1 | awk -F. '{print $1"."$2"."$3}')
          
          echo "Ищем диапазон для $TOTAL нод ($MASTERS мастер + $WORKERS воркер)"
          echo "Текущая база: $CURRENT_BASE"
          
          # Сначала проверяем текущий диапазон
          CURRENT_FREE=true
          for i in $(seq 0 $((TOTAL - 1))); do
            IP="$NETWORK_PREFIX.$((CURRENT_BASE + i))"
            if ping -c 1 -W 1 "$IP" &>/dev/null; then
              echo "❌ $IP занят"
              CURRENT_FREE=false
            fi
          done
          
          if [ "$CURRENT_FREE" = true ]; then
            echo "✅ Текущий диапазон свободен"
            exit 0
          fi
          
          echo "Текущий диапазон занят, ищем новый..."
          
          # Ищем свободный диапазон (от 100 до 240)
          for start in $(seq 100 240); do
            RANGE_FREE=true
            
            for offset in $(seq 0 $((TOTAL - 1))); do
              IP="$NETWORK_PREFIX.$((start + offset))"
              if ping -c 1 -W 1 "$IP" &>/dev/null; then
                RANGE_FREE=false
                break
              fi
            done
            
            if [ "$RANGE_FREE" = true ]; then
              echo "✅ Найден свободный диапазон: $start"
              
              # Обновляем config.auto.tfvars
              sed -i "s/static_ip_base  = $CURRENT_BASE/static_ip_base  = $start/" config.auto.tfvars
              
              echo "Обновлен static_ip_base на $start"
              echo "Новые IP:"
              for offset in $(seq 0 $((TOTAL - 1))); do
                ip=$((start + offset))
                if [ $offset -lt $MASTERS ]; then
                  echo "  Мастер $((offset+1)): $NETWORK_PREFIX.$ip"
                else
                  echo "  Воркер $((offset - MASTERS + 1)): $NETWORK_PREFIX.$ip"
                fi
              done
              
              # Показываем изменения
              echo "=== Изменения в config.auto.tfvars ==="
              grep "static_ip_base" config.auto.tfvars
              exit 0
            fi
          done
          
          echo "❌ Не удалось найти свободный диапазон"
          exit 1

      - name: Show Final Configuration
        run: |
          echo "=== Финальная конфигурация ==="
          cat config.auto.tfvars
          echo ""
          echo "=== IP адреса ==="
          grep "static_ip_base" config.auto.tfvars

      - name: Terraform Init
        run: terraform init
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
